hello_app/__init__.py
import flask

app = flask.Flask(__name__)
app.config['SECRET_KEY'] = 'cd668a81b31786c38b7187082b8633b0828f7adf97105432'
from hello_app.routes.ms_lic import bp_ms_lic
app.register_blueprint(bp_ms_lic, url_prefix="/ms")
from hello_app.helpers.ms_db import db, User, TenantSku

hello_app/routes/ms_lic.py
# from dataclasses import dataclass
# from hello_app.routes.forms import StudentForm
from flask import render_template, Blueprint, abort, request, redirect, url_for
from jinja2 import TemplateNotFound
from hello_app.helpers.ms_db import User, db, TenantSku
# from wtforms import Form

bp_ms_lic = Blueprint('ms_lic', __name__, template_folder='ms_lic')


@bp_ms_lic.route('/', methods=['GET', 'POST'])
def show_main():
    try:
        skus = TenantSku.query.all()
        if skus:
            return render_template(f'ms_lic.html', skus=skus)
        else:
            return render_template(f'ms_lic.html')
    except TemplateNotFound:
        abort(404)


@bp_ms_lic.route('/users', methods=['GET'])
def show_users():
    try:
        users = User.query.all()
        if users:
            return render_template(f'list_users.html', users=users)
        else:
            return render_template(f'list_users.html')
    except TemplateNotFound:
        abort(404)


@bp_ms_lic.route('/dbInit')
def init_ms_db():
    try:
        # init DB by adding fake data
        # TODO figure out if this is dangerous and refactor it properly.
        import hello_app.helpers.add_ms_db_data
        skus = TenantSku.query.all()
        # return render_template('forms/index.html', students=students)
        return render_template(f'ms_lic.html', skus=skus)
    except TemplateNotFound:
        abort(404)

hello_app/views.py
from datetime import datetime
from flask import render_template
from . import app


@app.route("/hello/")
@app.route("/hello/<name>")
def hello_there(name=None):
    return render_template(
        "hello_there.html",
        name=name,
        date=datetime.now()
    )


@app.route("/api/data")
def get_data():
    return app.send_static_file("data.json")

hello_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<title>{% block title %} {% endblock %} - FlaskApp</title>
		<style>
			.title {
				margin: 5px;
			}

			.content {
				margin: 5px;
				width: 100%;
				display: flex;
				flex-direction: row;
				flex-wrap: wrap;
			}

			.student {
				flex: 20%;
				padding: 10px;
				margin: 5px;
				background-color: #f3f3f3;
				inline-size: 100%;
			}

			.bio {
				padding: 10px;
				margin: 5px;
				background-color: #ffffff;
				color: #004835;
			}

			.name a {
				color: #00a36f;
				text-decoration: none;
			}

			nav a {
				color: #d64161;
				font-size: 3em;
				margin-left: 50px;
				text-decoration: none;
			}
		</style>
	</head>
	<body>
		<nav>
			<a href="{{ url_for('ms_lic.show_main') }}">FlaskApp</a>
			<a href="#">About</a>
		</nav>
		<hr />
		<div class="content">{% block content %} {% endblock %}</div>
	</body>
</html>

hello_app/templates/list_users.html
{% extends 'base.html' %} {% block content %}
<h1 class="title">{% block title %} MS User Status {% endblock %}</h1>

{% if users is defined %}
<div class="content">
	{% for user in users %}
	<div class="student">
		<p>User Name:{{ user.displayname }}</p>
		<p>Licenses:{{ user.sku_names }}</p>
		<p>Tenant:{{ user.tenant_name }}</p>
		<p>Email Address:{{ user.email }}</p>
	</div>
	{% endfor %}
</div>
{% else %}
<div class="content">
	<p>DB To be initiated?</p>
	<form action="{{ url_for('ms_lic.init_ms_db') }}" method="get">
		<button>Init the DB</button>
	</form>
</div>
{% endif %} {% endblock %}

hello_app/templates/ms_lic.html
{% extends 'base.html' %} {% block content %}
<h1 class="title">{% block title %} MS License Status {% endblock %}</h1>

{% if skus is defined %}
<div class="content">
	{% for sku in skus %}
	<div class="student">
		<p>Tenant Name:{{ sku.tenant_name }}</p>
		<p>License Name:{{ sku.sku_name }}</p>
		<p>Licenses In Use:{{ sku.consumed }}</p>
		<p>Licenses Over Subscribed:{{ sku.warning }}</p>
		<p>Licenses Available:{{ sku.enabled }}</p>
		<p>Licenses Suspended:{{ sku.suspended }}</p>
	</div>
	{% endfor %}
</div>
{% else %}
<div class="content">
	<p>DB To be initiated?</p>
	<form action="{{ url_for('ms_lic.init_ms_db') }}" method="get">
		<button>Init the DB</button>
	</form>
</div>
{% endif %} {% endblock %}

hello_app/templates/page_user.html
{% extends 'base.html' %} {% block content %}
<span class="title">
	<h1>
		{% block title %} {{ student.firstname }} {{ student.lastname }}{% endblock
		%}
	</h1>
</span>
<div class="content">
	<div class="student">
		<p><b>#{{ student.id }}</b></p>
		<b>
			<p class="name">{{ student.firstname }} {{ student.lastname }}</p>
		</b>
		<p>{{ student.email }}</p>
		<p>{{ student.age }} years old.</p>
		<p>Joined: {{ student.created_at }}</p>
		<div class="bio">
			<h4>Bio</h4>
			<p>{{ student.bio }}</p>
		</div>
	</div>
</div>
{% endblock %}